
[mana]
	#Hide the mana bar if it has not changed for the set amount of time (in ticks, 1 second = 20 ticks). Set to 0 to always have it visible.
	#Range: 0 ~ 1200
	hideDelay = 0
	#Put the mana bar above the food/health bar (true) or else put it below (false).
	guiAboveFood = true
	#Put the mana bar next to the health bar (true) or else leave it next to the food bar (false).
	guiByHealth = false
	#The mana bar icons jitter when your current mana is low (true) or else the icons always stay put (false).
	jitter = true

#Everything about the gui widgets representing your spell slots (equipped spells)
[spellSlots]
	#Always show all spell slots (true) or else only show them if at least 1 spell is equipped (false).
	alwaysShow = true

	#The position to put the spell slots in the survival inventory gui.
	[spellSlots.survival]
		#These values represent the position by going counter-clockwise around the gui with 3 available positions on each side. 0-11 attaches it to the edge of the inventory gui, 12-23 to the edge of the screen.
		#Range: 0 ~ 23
		position = 0
		#Manually move the x position of the spell slots by the set amount.
		#Range: -800 ~ 800
		offsetX = 0
		#Manually move the y position of the spell slots by the set amount.
		#Range: -800 ~ 800
		offsetY = 0
		#The spacing between the spell slots.
		#Range: 0 ~ 10
		spacing = 1

	#The position to put the spell slots in the creative inventory gui.
	[spellSlots.creative]
		#These values represent the position by going counter-clockwise around the gui with 3 available positions on each side. 0-11 attaches it to the edge of the inventory gui, 12-23 to the edge of the screen.
		#Range: 0 ~ 23
		position = 0
		#Manually move the x position of the spell slots by the set amount.
		#Range: -800 ~ 800
		offsetX = 0
		#Manually move the y position of the spell slots by the set amount.
		#Range: -800 ~ 800
		offsetY = 0
		#The spacing between the spell slots.
		#Range: 0 ~ 10
		spacing = 1

#Settings relevant for data pack creators.
[technical]
	#Show spell and spell node IDs.
	showIds = false

